# Generated by Django 5.0.4 on 2024-04-22 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_category_alter_packages_content_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.FloatField(default=0.0)),
                ('price_origin', models.FloatField(null=True)),
                ('image', models.ImageField(default='store/images/default.png', upload_to='store/images')),
                ('content', models.TextField(blank=True, null=True)),
                ('public_day', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.IntegerField(default=0)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Store.subcategory')),
            ],
            options={
                'ordering': ('-public_day',),
            },
        ),
        migrations.DeleteModel(
            name='Packages',
        ),
    ]
