# Generated by Django 5.0.4 on 2024-04-22 19:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_product_delete_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(max_length=100)),
                ('duration_days', models.IntegerField()),
                ('duration_date', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('num_person', models.IntegerField()),
                ('image', models.ImageField(upload_to='packages_img/')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('read_more_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
