# Generated by Django 5.0.4 on 2024-04-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_remove_subcategory_category_remove_subcategory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='Store/images/destination.png', upload_to='Store/images'),
        ),
    ]
