# Generated by Django 5.0.4 on 2024-04-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
