# Generated by Django 5.0.4 on 2024-04-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_remove_destination_image_destinationimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='name',
        ),
        migrations.DeleteModel(
            name='DestinationImage',
        ),
    ]
