# Generated by Django 5.0.4 on 2024-04-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_destinationimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='duration_days',
            field=models.CharField(max_length=100),
        ),
    ]
