# Generated by Django 5.0.4 on 2024-04-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_alter_packages_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
