# Generated by Django 5.0.4 on 2024-04-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0017_packages_price_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='price_old',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
