# Generated by Django 5.0.4 on 2024-04-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0018_alter_packages_price_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationimage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
