# Generated by Django 5.0.4 on 2024-04-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0020_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='destination_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
