# Generated by Django 5.0.4 on 2024-04-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0021_alter_carousel_destination_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='packages',
            name='price_old',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
