# Generated by Django 5.0.4 on 2024-05-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0024_booking_booking_at_contact_contact_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_at',
        ),
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='packages',
            name='price_old',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
