# Generated by Django 5.0.4 on 2024-05-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0026_carousel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationimage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
