# Generated by Django 5.0.4 on 2024-05-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0027_alter_destinationimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='price_old',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
