# Generated by Django 5.0.4 on 2024-05-01 21:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0029_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
