# Generated by Django 5.0.4 on 2024-05-02 19:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0030_alter_terms_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
