# Generated by Django 5.0.4 on 2024-05-04 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0032_contact_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
    ]
